### ISSUE TITLE
Icons are not render

### ISSUE THREAD

**Issue by groteck** [code-farmer-i/vue-markdown-editor#146]
I'm using nuxt 3 (maybe that is the issue) but I can render the editor with the only problem that the toolbar icons are not render.

![image](https://user-images.githubusercontent.com/833030/150954805-9d7a2f5b-d6a5-4b6d-b8b4-2548bd656a1f.png)

**Comment by groteck** [comment]
I assigned a css rule with a custom font in my globals:
```css
*, *:before, *:after {
}
```
Since the icons are render in the `:before` the css rule:

```css
[class*=v-md-icon-] {
    font-size: 16px;
    font-family: v-md-iconfont!important;
    font-style: normal!important;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

doesn't take precedence over `*:before`.

I fixed adding this to my global css fonts:

```css
 [class*=v-md-icon-], [class*=v-md-icon-]:before, [class*=v-md-icon-]:after {
      font-size: 16px;
      font-family: v-md-iconfont!important;
      font-style: normal!important;
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
  }
```
