### ISSUE TITLE
Dark Mode?

### ISSUE THREAD

**Issue by ajmas** [code-farmer-i/vue-markdown-editor#219]
Any suggestion on being able to have the editor automatically render in dark mode, such that it becomes white text on black background? Both for view and editor modes.

I am currently using the vue-press theme, if it impacts the answer.

**Comment by ajmas** [comment]
I didn't find anything built in so I just put some SCSS together that works for my needs:

```scss
@media (prefers-color-scheme: dark) {
  .v-md-editor {
    background-color: transparent !important;
  }
  .v-md-editor.v-md-editor--edit {
    background-color: transparent;
  }
  .v-md-editor__toolbar {
    background-color: transparent;
    color: white;
  }
  .v-md-textarea-editor textarea{
    background-color: transparent;
    color: white !important;
  }

  .vuepress-markdown-body {
    background-color: transparent !important;;
    color: white !important;
  }
}
```

At the same time, I am going to look into whether there is a version of the Vue-Press theme that already deal with the 'prefers dark mode' media selector.

In general, would there be any interest in adding dark mode as an option, either for the editor or an updated Vue-Press theme?
