### ISSUE TITLE
Hide Toolbar 

### ISSUE THREAD

**Issue by aakritsubedi** [code-farmer-i/vue-markdown-editor#96]
Option to hide toolbar so that we can only use the text editor.

**Comment by code-farmer-i** [comment]
```css
.v-md-editor__toolbar {
  display: none;
}
```
